apiVersion: v1
kind: Config
clusters:
  - name: webhook-authn
    cluster:
      insecure-skip-tls-verify: true
      server: https://d960-223-190-85-35.ngrok-free.app/auth
users:
  - name: webhook-user
contexts:
  - name: webhook-context
    context:
      cluster: webhook-authn
      user: webhook-user
current-context: webhook-context